fix(beta-check): embed bash script in action
we can't access the script file from the consumer running this action

diff --git a/lint/action.yaml b/lint/action.yaml
--- a/lint/action.yaml
+++ b/lint/action.yaml
@@ -73,5 +73,10 @@ runs:
       uses: open-turo/action-pre-commit@v1
     - if: ${{ inputs.internal-dependency-prefixes != '' }}
       name: Beta Release Check
-      run: ./lint/scripts/beta-check.sh ${{ inputs.internal-dependency-prefixes }}
+      run: |
+        delimited_prefixes=$(sed 's/ *, */|/g' <<< ${{ inputs.internal-dependency-prefixes }})
+        if egrep "($delimited_prefixes).*\-beta\-" package.json; then
+          echo "ERROR: should not consume a beta version of an internal dependency. Make sure to revert/update to use a proper release."
+          exit 1
+        fi
       shell: bash
